In [1]:
import gymnasium as gym
import numpy as np
from gymnasium import spaces

/usr/local/lib/python3.11/dist-packages/gymnasium/envs/registration.py:596: UserWarning: WARN: plugin: shimmy.registration:register_gymnasium_envs raised Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/gymnasium/envs/registration.py", line 594, in load_plugin_envs
    fn()
  File "/usr/local/lib/python3.11/dist-packages/shimmy/registration.py", line 304, in register_gymnasium_envs
    _register_atari_envs()
  File "/usr/local/lib/python3.11/dist-packages/shimmy/registration.py", line 205, in _register_atari_envs
    import ale_py
  File "/usr/local/lib/python3.11/dist-packages/ale_py/__init__.py", line 68, in <module>
    register_v0_v4_envs()
  File "/usr/local/lib/python3.11/dist-packages/ale_py/registration.py", line 179, in register_v0_v4_envs
    _register_rom_configs(legacy_games, obs_types, versions)
  File "/usr/local/lib/python3.11/dist-packages/ale_py/registration.py", line 64, in _register_rom_configs
    gymnasium.register(
    ^^^^^^^^^^^

In [2]:
class tictactoe(gym.Env):
    def __init__(self):
        super().__init__()
        self.observation_space = spaces.Box(low = 0, high = 2, shape = (3,3), dtype = np.int32)
        self.action_space = spaces.Discrete(9)
        self.win_reward = 1
        self.lose_reward = -1
        self.draw_reward = 0
        
        self.observation = np.zeros(shape = (3,3), dtype = np.int32)
        self.player = 1
        self.terminated = False
        self.truncated = False

        
    def reset(self):
        self.observation = np.zeros(shape = (3,3), dtype = np.int32)
        self.player = 1
        self.terminated = False
        self.truncated = False
        return self.observation

    def check(self,observation, player):
        finish = True
        for i in range(3):
            for j in range(3):
                if observation[i][j] == 0:
                    finish = False
                    break
            if not finish:
                break

        won = True
        for i in range(3):
            won = True
            for j in range(3):
                if observation[i][j] != player:
                    won = False
                    break
            if won:
                return self.win_reward, True

        for i in range(3):
            won = True
            for j in range(3):
                if observation[j][i] != player:
                    won = False
                    break
            if won:
                return self.win_reward, True

        won = True
        for i in range(3):
            if observation[i][i] != player:
                won = False
                break
        if won:
            return self.win_reward, True

        for i in range(3):
            if observation[i][2-i] != player:
                won = False
                break
        if won:
            return self.win_reward, True

        if finish:
            return 0, True
        else:
            return 0, False
    

    def step(self,action):
        if self.observation[action//3][action%3] != 0:
            self.truncated = True
            self.terminated = True
        self.observation[action//3][action%3] = self.player

        reward, done = self.check(self.observation, self.player)
        self.player=self.player%2+1
        if done:
            self.truncated = True
            self.terminated = True
        return self.observation, reward, self.truncated, self.terminated,

In [3]:
import random
env = tictactoe()
env.observation

for i in range(10):
    done = False
    env.reset()
    print('Episode number',i)
    while not done:
        
        possible_actions = []
        for i in range(9):
            if env.observation[i//3][i%3] == 0:
                possible_actions.append(i)
        action = random.choice(possible_actions)
        observation, reward, trunc, terminated = env.step(action)
        print(observation, reward, trunc, terminated)
        if trunc:
            done = True


Episode number 0
[[0 0 0]
 [0 0 1]
 [0 0 0]] 0 False False
[[0 0 0]
 [0 2 1]
 [0 0 0]] 0 False False
[[0 1 0]
 [0 2 1]
 [0 0 0]] 0 False False
[[0 1 0]
 [0 2 1]
 [0 2 0]] 0 False False
[[0 1 1]
 [0 2 1]
 [0 2 0]] 0 False False
[[0 1 1]
 [2 2 1]
 [0 2 0]] 0 False False
[[0 1 1]
 [2 2 1]
 [0 2 1]] 1 True True
Episode number 1
[[0 0 0]
 [0 0 0]
 [0 1 0]] 0 False False
[[0 0 0]
 [2 0 0]
 [0 1 0]] 0 False False
[[0 0 1]
 [2 0 0]
 [0 1 0]] 0 False False
[[0 2 1]
 [2 0 0]
 [0 1 0]] 0 False False
[[1 2 1]
 [2 0 0]
 [0 1 0]] 0 False False
[[1 2 1]
 [2 2 0]
 [0 1 0]] 0 False False
[[1 2 1]
 [2 2 1]
 [0 1 0]] 0 False False
[[1 2 1]
 [2 2 1]
 [0 1 2]] 0 False False
[[1 2 1]
 [2 2 1]
 [1 1 2]] 0 True True
Episode number 2
[[0 0 0]
 [1 0 0]
 [0 0 0]] 0 False False
[[0 0 0]
 [1 0 2]
 [0 0 0]] 0 False False
[[0 0 0]
 [1 1 2]
 [0 0 0]] 0 False False
[[2 0 0]
 [1 1 2]
 [0 0 0]] 0 False False
[[2 0 0]
 [1 1 2]
 [0 0 1]] 0 False False
[[2 0 0]
 [1 1 2]
 [0 2 1]] 0 False False
[[2 0 1]
 [1 1 2]
 [0 2 1]] 0

In [4]:
env.reset()
env.step(0)
env.step(4)
env.step(1)
env.step(3)
print(env.step(2))


(array([[1, 1, 1],
       [2, 2, 0],
       [0, 0, 0]], dtype=int32), 1, True, True)
